### ISSUE TITLE
`repo.clear!` throws exception

### ISSUE THREAD

**Issue by igravious** [ruby-rdf/rdf-do#5]
undefined method `each' for nil:NilClass
/home/groobiest/huh/vendor/cache/ruby/2.3.0/gems/rdf-2.2.11/lib/rdf/model/dataset.rb:67:in `each_statement'
/home/groobiest/huh/vendor/cache/ruby/2.3.0/gems/rdf-2.2.11/lib/rdf/mixin/mutable.rb:288:in `delete_statements'
/home/groobiest/huh/vendor/cache/ruby/2.3.0/gems/rdf-2.2.11/lib/rdf/mixin/mutable.rb:238:in `clear'
/home/groobiest/huh/vendor/cache/ruby/2.3.0/gems/rdf-2.2.11/lib/rdf/util/aliasing.rb:46:in `block in alias_method'
/home/groobiest/huh/lib/tasks/triples.rake:51:in `block (2 levels) in &lt;main&gt;'

**Comment by gkellogg** [comment]
Closed along with #4 by a change to RDF.rb.
